<script language="JavaScript" src="/template/xp_progress.js"></script>

   <center>
   <table border="1"
          style="background: red;
                 border: 5px ridge black;
                 border-collapse: collapse;">
   <tr>
   <td align="center"
       style="color: 0;
              font-family: Verdana, Arial, Helvetica, sans-serif;">
   <font size="4"><b>Uploading File....</b></font><br>
<script type="text/javascript">
   var uploadXPBar= createBar(300,15,'white',1,'black','blue',85,7,3,"");
</script>
   <font size="2">Please Wait!</font>
   </td>
   </tr>
   </table>
   </center>
