   <center>
   <table border="1"
          style="background: red;
                 border: 5px ridge black;
                 border-collapse: collapse;">
   <tr>
   <td align="center"
       style="color: 0;
              font-family: Verdana, Arial, Helvetica, sans-serif;">
   <font size="4"><b>Uploading File....</b></font><br>
   <img src="/images/await.gif" border="0"><br>
   <font size="2">Please Wait!</font>
   </td>
   </tr>
   </table>
   </center>